---

- name: get oh-my-zsh script
  get_url: url=http://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh dest=/tmp/oh-my-zsh.sh

- name: change file permission to be executable
  command: chmod +x /tmp/oh-my-zsh.sh

- name: install zsh
  script: /tmp/oh-my-zsh.sh

- name: Clone dotfiles
  git: repo=https://github.com/jeslopcru/dotfiles.git dest=~/dotfiles recursive=yes update=no

- name: using custom zsh config
  command: cd ~/dotfiles && stow zsh

- name: using custom vim config
  command: cd ~/dotfiles && stow vim

- name: using custom git config
  command: cd ~/dotfiles && stow git

- name: Set datetime zone
  lineinfile: dest=/usr/local/etc/php/7.0/php.ini line="date.timezone=Europe/Madrid"

- name: Install npm packages
  npm:  name={{ item }} global=yes
  with_items: "{{ npm_packages }}"